apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: hub
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
      - image: docker.io/registry
        ports:
        - containerPort: 5000
