#Builds an image and push it to registry.
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-push
spec:
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v0.9.0
    args:
    - --destination=hub-default.${DOMAIN}:443/hello
    - --context=/workspace/workspace
    volumeMounts:
    - name: source
      mountPath: /workspace/workspace
  volumes:
  - name: source
    configMap:
      name: source

---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-image
spec:
  taskRef:
    name: build-push
